---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Podcasts
  - TV
  - Maps
  - Photos
  - Safari
  - Mail
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - Keynote
  - Numbers
  - Pages
dockitems_persist:
  - name: "Visual Studio Code - Insiders"
    path: "/Applications/Visual Studio Code - Insiders.app/"
    pos: 1

configure_sudoers: true
# sudoers_custom_config: ''
# Example:
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/roycastro/mac-dev-dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles/configs
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .nvmrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - zsh-history-substring-search
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - angular-cli
  - terraform
  - firebase-cli
  - openvpn
  - instantclient-basic
  - instantclient-sqlplus
  - ansible-lint
  - coreutils
  - jq

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-versions
  - InstantClientTap/instantclient
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-cloud-sdk
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - slack
  - iterm2
  - github
  - microsoft-teams
  - zoom
  - keka
  - postman
  - vlc
  - android-sdk
  - qbittorrent
  - tor-browser
  - macs-fan-control
  - visual-paradigm
  - visual-studio-code-insiders
  - google-drive
  - telegram
  - viscosity
  - flutter
  - licecap
  - kodi
  - obs
  - font-fira-code
  - lens
  - dbeaver-community
  - royal-tsx
  - yandex-cloud-cli
  - rectangle
  - tunnelblick

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1147396723, name: "WhatsApp Desktop" }
  - { id: 425264550, name: "Blackmagic Disk Speed Test" }
  - { id: 882812218, name: "Owly - Prevent Display Sleep" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: [ "tasks/post-tasks.yml"]
